url: "http://catsharkconsulting.com"
title: "Catshark Consulting"
author: "R. Scott Reis"
long_desc: >-
  Catshark Consulting provides digital services to Seattle-area nonprofits and community organizations.
  We support your mission by improving access to technology and the advantages it provides.
short_desc: 'Digital consulting for Seattle-area nonprofits'
permalink: /blog/:title/
